name: build-test
on: push

jobs:
  buildTest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        compiler: [g++]
        language: ['cpp']
        
    steps:
    
    - name: Install CMake
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq cmake
        cmake --version
        /usr/bin/cmake --version

    - name: Install mpi
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq mpich libmpich-dev
        
    - name: Kokkos Checkout repo
      uses: actions/checkout@v3
      with:
        repository: kokkos/kokkos
        path: kokkos

    - name: Kokkos Create Directory
      run: cmake -E make_directory build-kokkos

    - name: Kokkos Configure CMake
      run: /usr/bin/cmake -S kokkos -B build-kokkos
        -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
        -DKokkos_ENABLE_SERIAL=ON
        -DKokkos_ENABLE_OPENMP=off
        -DKokkos_ENABLE_CUDA=off
        -DKokkos_ENABLE_CUDA_LAMBDA=off
        -DKokkos_ENABLE_DEBUG=on
        -DCMAKE_INSTALL_PREFIX=build-kokkos/install
    
    - name: Kokkos Build
      run: /usr/bin/cmake --build build-kokkos -j8 --target install
  