name: build-test
on: push

jobs:
  buildTest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        compiler: [g++]
        language: ['cpp']
        
    steps:
    
    - name: Install CMake
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq cmake
        cmake --version
        /usr/bin/cmake --version

    - name: Install mpi
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq mpich libmpich-dev

    # Build Kokkos
        
    - name: Kokkos Checkout repo
      uses: actions/checkout@v3
      with:
        repository: kokkos/kokkos
        path: kokkos

    - name: Kokkos Create Directory
      run: cmake -E make_directory ${{ runner.temp }}/build-kokkos

    - name: Kokkos Configure CMake
      run: cmake -S $GITHUB_WORKSPACE/kokkos -B ${{ runner.temp }}/build-kokkos
        -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}/build-kokkos/install
        -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
        -DKokkos_ENABLE_SERIAL=ON
        -DKokkos_ENABLE_OPENMP=off
        -DKokkos_ENABLE_CUDA=off
        -DKokkos_ENABLE_CUDA_LAMBDA=off
        -DKokkos_ENABLE_DEBUG=on
    
    - name: Kokkos Build
      run: cmake --build ${{ runner.temp }}/build-kokkos -j8 --target install

    # Build EnGPar
        
    - name: EnGPar Checkout repo
      uses: actions/checkout@v3
      with:
        repository: SCOREC/EnGPar
        path: engpar

    - name: EnGPar Create Directory
      run: cmake -E make_directory ${{ runner.temp }}/build-engpar

    - name: EnGPar Configure CMake
      run: cmake -S $GITHUB_WORKSPACE/engpar -B ${{ runner.temp }}/build-engpar
        -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}/build-engpar/install
        -DCMAKE_C_COMPILER="mpicc"
        -DCMAKE_CXX_COMPILER="mpicxx"
        -DCMAKE_CXX_FLAGS="-std=c++11"
        -DENABLE_PARMETIS=OFF
        -DENABLE_PUMI=OFF
        -DIS_TESTING=OFF
    
    - name: EnGPar Build
      run: cmake --build ${{ runner.temp }}/build-engpar -j8 --target install

    # Build Omega_h
        
    - name: Omega_h Checkout repo
      uses: actions/checkout@v3
      with:
        repository: sandialabs/omega_h
        path: omega_h

    - name: Omega_h Create Directory
      run: cmake -E make_directory ${{ runner.temp }}/build-omega_h

    - name: Omega_h Configure CMake
      run: cmake -S $GITHUB_WORKSPACE/omega_h -B ${{ runner.temp }}/build-omega_h
        -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}/build-omega_h/install
        -DCMAKE_PREFIX_PATH=${{ runner.temp }}/build-kokkos/install/lib/cmake
        -DBUILD_SHARED_LIBS=OFF
        -DOmega_h_USE_Kokkos=ON
        -DOmega_h_USE_CUDA=off
        -DOmega_h_USE_MPI=on
        -DCMAKE_BUILD_TYPE=Debug
        -DBUILD_TESTING=on
        -DCMAKE_CXX_COMPILER="mpicxx"
        -DCMAKE_C_COMPILER="mpicc"
    
    - name: Omega_h Build
      run: cmake --build ${{ runner.temp }}/build-omega_h -j8 --target install

    # Build PUMI-PIC
        
    - name: PUMI-PIC Checkout repo
      uses: actions/checkout@v3
      with:
        repository: SCOREC/pumi-pic
        path: pumi-pic

    - name: PUMI-PIC Create Directory
      run: cmake -E make_directory ${{ runner.temp }}/build-pumi-pic

    - name: PUMI-PIC Configure CMake
      run: cmake -S $GITHUB_WORKSPACE/pumi-pic -B ${{ runner.temp }}/build-pumi-pic
        -DCMAKE_CXX_COMPILER=mpicxx  \
        -DIS_TESTING=ON  \
        -DPS_IS_TESTING=ON  \
        -DCMAKE_BUILD_TYPE=Debug  \
        -DTEST_DATA_DIR=$GITHUB_WORKSPACE/pumi-pic/pumipic-data  \
        -DOmega_h_PREFIX=${{ runner.temp }}/build-omega_h/install  \
        -DKokkos_PREFIX=${{ runner.temp }}/build-kokkos/install  \
        -DEnGPar_PREFIX=${{ runner.temp }}/build-engpar/install  \
        -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}/build-pumi-pic/install
    
    - name: PUMI-PIC Build
      run: cmake --build ${{ runner.temp }}/build-pumi-pic -j8 --target install

    - name: PUMI-PIC Test
      run: ctest --test-dir ${{ runner.temp }}/build-pumi-pic
  