name: build-test
on: push

jobs:
  buildTest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        compiler: [g++]
        language: ['cpp']
        
    steps:
    
    - name: Install CMake
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq cmake
        cmake --version
        /usr/bin/cmake --version

    - name: Install mpi
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq mpich libmpich-dev

    # Build Kokkos
        
    - name: Kokkos Checkout repo
      uses: actions/checkout@v3
      with:
        repository: kokkos/kokkos
        path: kokkos

    - name: Kokkos Create Directory
      run: cmake -E make_directory build-kokkos

    - name: Kokkos Configure CMake
      run: cmake -S kokkos -B build-kokkos
        -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
        -DKokkos_ENABLE_SERIAL=ON
        -DKokkos_ENABLE_OPENMP=off
        -DKokkos_ENABLE_CUDA=off
        -DKokkos_ENABLE_CUDA_LAMBDA=off
        -DKokkos_ENABLE_DEBUG=on
        -DCMAKE_INSTALL_PREFIX=build-kokkos/install
    
    - name: Kokkos Build
      run: cmake --build build-kokkos -j8 --target install

    # Build EnGPar
        
    - name: EnGPar Checkout repo
      uses: actions/checkout@v3
      with:
        repository: SCOREC/EnGPar
        path: engpar

    - name: EnGPar Create Directory
      run: cmake -E make_directory build-engpar

    - name: EnGPar Configure CMake
      run: cmake -S engpar -B build-engpar
        -DCMAKE_INSTALL_PREFIX=build-engpar/install
        -DCMAKE_C_COMPILER="mpicc"
        -DCMAKE_CXX_COMPILER="mpicxx"
        -DCMAKE_CXX_FLAGS="-std=c++11"
        -DENABLE_PARMETIS=OFF
        -DENABLE_PUMI=OFF
        -DIS_TESTING=OFF
    
    - name: EnGPar Build
      run: cmake --build build-engpar -j8 --target install

    # Build Omega_h
        
    - name: Omega_h Checkout repo
      uses: actions/checkout@v3
      with:
        repository: sandialabs/omega_h
        path: omega_h

    - name: Omega_h Create Directory
      run: cmake -E make_directory build-omega_h

    - name: Omega_h Configure CMake
      run: cmake -S omega_h -B build-omega_h
        -DCMAKE_INSTALL_PREFIX=build-omega_h/install
        -DBUILD_SHARED_LIBS=OFF
        -DOmega_h_USE_Kokkos=ON
        -DOmega_h_USE_CUDA=off
        -DOmega_h_USE_MPI=on
        -DCMAKE_BUILD_TYPE=Debug
        -DBUILD_TESTING=on
        -DCMAKE_CXX_COMPILER="mpicxx"
        -DCMAKE_C_COMPILER="mpicc"
        -DCMAKE_INSTALL_PREFIX=build-kokkos/install/lib64/cmake/Kokkos
        -DKokkos_PREFIX=build-kokkos/install/lib64/cmake/Kokkos
    
    - name: Omega_h Build
      run: cmake --build build-omega_h -j8 --target install

    - name: Omega_h Test
      run: ctest --test-dir build-omega_h
  