name: build-test
on: push

jobs:
  buildTest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        compiler: [g++]
        language: ['cpp']
        
    steps:
    
    - name: Install CMake
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq cmake
        cmake --version
        /usr/bin/cmake --version

    - name: Install mpi
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq mpich libmpich-dev

    # Build Kokkos
        
    - name: Kokkos Checkout repo
      uses: actions/checkout@v3
      with:
        repository: kokkos/kokkos
        path: kokkos

    - name: Kokkos Create Directory
      run: cmake -E make_directory build-kokkos

    - name: Kokkos Configure CMake
      run: cmake -S kokkos -B build-kokkos
        -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
        -DKokkos_ENABLE_SERIAL=ON
        -DKokkos_ENABLE_OPENMP=off
        -DKokkos_ENABLE_CUDA=off
        -DKokkos_ENABLE_CUDA_LAMBDA=off
        -DKokkos_ENABLE_DEBUG=on
        -DCMAKE_INSTALL_PREFIX=build-kokkos/install
    
    - name: Kokkos Build
      run: cmake --build build-kokkos -j8 --target install

    # Build EnGPar
        
    - name: EnGPar Checkout repo
      uses: actions/checkout@v3
      with:
        repository: SCOREC/EnGPar
        path: engpar

    - name: EnGPar Create Directory
      run: cmake -E make_directory build-engpar

    - name: EnGPar Configure CMake
      run: cmake -S engpar -B build-engpar
        -DCMAKE_INSTALL_PREFIX=build-engpar/install
        -DCMAKE_C_COMPILER="mpicc"
        -DCMAKE_CXX_COMPILER="mpicxx"
        -DCMAKE_CXX_FLAGS="-std=c++11"
        -DENABLE_PARMETIS=OFF
        -DENABLE_PUMI=OFF
        -DIS_TESTING=OFF
    
    - name: EnGPar Build
      run: cmake --build build-engpar -j8 --target install
  